version: 2
updates:
  # Check for Python dependencies updates (using pip)
  - package-ecosystem: "pip"
    directory: "/"  # Location of your pyproject.toml file
    schedule:
      interval: "weekly"  # You can also use "daily" or "monthly"

  # Check for GitHub Actions updates
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"  # Regular checks for GitHub Actions updates
