version: '3.8'

services:
  pomodoro-pytest:
    build:
      context: .
      target: pomodoro-test  # Build stage to use for pytest
      args:
        MODULE_GROUP: pomodoro  # Use development dependencies for testing
    volumes:
      - .:/app:Z  # Mount the current directory to the container for testing
    environment:
      - PYTHONPATH=/app/src:/app
    command: ["poetry", "run", "pytest"]  # For running pytest


  pomodoro-behave:
    build:
      context: .
      target: pomodoro-test  # Build stage to use for behave
      args:
        MODULE_GROUP: pomodoro  # Use development dependencies for testing
    volumes:
      - .:/app:Z  # Mount the current directory to the container for testing
    environment:
      - PYTHONPATH=/app/src:/app
    command: ["poetry", "run", "behave"]  # For running behave

  pomodoro-app:
    build:
      context: .
      target: pomodoro  # Use the pomodoro build stage
      args:
        MODULE_GROUP: pomodoro  # Use runtime dependencies
    volumes:
      - .:/app:Z  # Mount the current directory
      - /dev/snd:/dev/snd  # Forward the sound device
    devices:
      - /dev/snd
    environment:
      - PYTHONPATH=/app/src:/app
      - AUDIO_OUTPUT=dummy
      - SDL_AUDIODRIVER=dummy  # Force pygame to use a virtual audio driver
    command: ["sh", "-c", "poetry run python -m run pomodoro -m $MINS"]
