name: Python Static Code Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out repository
      - name: Check out repository
        uses: actions/checkout@v4

      # Step 2: Set up Python 3.11
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Step 3: Install Poetry
      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      # Step 4: Install dependencies with Poetry (including dev dependencies)
      - name: Install dependencies
        run: |
          poetry install

      # Step 5: Run flake8 for static analysis
      - name: Run flake8
        run: |
          poetry run flake8 .

      # Step 6: Run pytest with coverage
      - name: Run pytest with coverage
        run: |
          poetry run pytest --cov=src --cov-report=xml --cov-fail-under=0

      # Step 7: Check if coverage is below 80%
      - name: Check if coverage is below 80
        run: |
          coverage=$(pytest --cov=src --cov-report=xml | tee result.log | tail -n 10)
          coverage_percentage=$(echo "$coverage" | grep -oP 'TOTAL\s+\K[0-9.]+')
          if [[ "$coverage_percentage" != "0" && $(echo "$coverage_percentage >= 80" | bc -l) -ne 1 ]]; then
            echo "Error: Coverage is below the acceptable thresholds (0% or >=80%). Coverage: $coverage_percentage%"
            exit 1
          fi

      # Step 8: Upload coverage results to GitHub (optional, for viewing coverage reports in the GitHub UI)
      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v3
        with:
          file: coverage.xml
