name: Python Static Code Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out repository
      - name: Check out repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # Specify your Python version

      # Step 3: Install Poetry
      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      # Step 4: Install dependencies (including development dependencies)
      - name: Install dependencies
        run: |
          poetry install

      # Step 5: Run flake8 for static analysis
      - name: Run flake8
        run: |
          poetry run flake8 .
