name: Python Package Unit Tests

# Trigger the workflow on push and pull request events
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Define the jobs that the workflow will run
jobs:
  test:
    # Specify the operating system to run the tests on
    runs-on: ubuntu-latest

    # Define steps for the job
    steps:
      # Step 1: Check out the code from the repository
      - name: Check out repository
        uses: actions/checkout@v3

      # Step 2: Set up Python with the version you need
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # Specify the version you want (e.g., 3.8, 3.9, 3.10)

      # Step 3: Install dependencies (use a requirements.txt file or a setup.py file)
      - name: Install dependencies
        run: |
          python -m pip install poetry install

      # Step 4: Run the unit tests (ensure you have a testing framework like pytest)
      - name: Run tests
        run: |
          pytest